#include "ClangIndexer.h"

#include "clang/AST/AST.h"
//#include "clang/AST/ASTConsumer.h"
//#include "clang/AST/Mangle.h"
//#include "clang/AST/RecursiveASTVisitor.h"
//#include "clang/Frontend/CompilerInstance.h"
//#include "clang/Frontend/FrontendAction.h"
//#include "clang/Lex/PPCallbacks.h"
//#include "clang/Lex/Preprocessor.h"
//#include "clang/Rewrite/Core/Rewriter.h"